#!/usr/bin/env python3
"""
Generate docs/API.md from the docstrings in the source tree.

    python3 tools/gen_api_docs.py           # rewrite docs/API.md
    python3 tools/gen_api_docs.py --check   # list undocumented items, exit 1 if any

Uses `ast` only, so it runs without GTK, evdev or a mouse attached.
Docstrings are the single source of truth: document code in the code,
then re-run this script.
"""

import ast
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "API.md")

# Reading order: low level first.
MODULES = [
    ("appinfo.py", "Branding & paths"),
    ("hidpp.py", "HID++ transport and device features"),
    ("onboard.py", "Onboard-memory profile format"),
    ("devices.py", "Per-model metadata"),
    ("keys.py", "Key tables"),
    ("macros.py", "Macro model & storage"),
    ("macro_engine.py", "Macro playback engine"),
    ("o2hubd.py", "Background service entry point"),
    ("service.py", "systemd user-service control"),
    ("scroll_quirk.py", "Notched scrolling (libinput quirk)"),
    ("mouse_art.py", "Mouse artwork"),
    ("app.py", "Main application UI"),
    ("macro_ui.py", "Macro editor UI"),
    ("diagnostics.py", "Diagnostics script"),
    ("test_macros.py", "Macro engine self-test"),
    ("main.py", "Launcher"),
    ("tools/gen_api_docs.py", "Docs generator (this reference)"),
    ("tools/ui_snapshot.py", "Screenshot tool"),
    ("tools/clear_background.py", "Photo background remover"),
]


def signature(fn):
    """Render a FunctionDef's parameters like Python source."""
    a = fn.args
    parts = []
    pos = a.posonlyargs + a.args
    defaults = [None] * (len(pos) - len(a.defaults)) + list(a.defaults)
    for arg, d in zip(pos, defaults):
        parts.append(arg.arg + (f"={ast.unparse(d)}" if d is not None else ""))
    if a.vararg:
        parts.append("*" + a.vararg.arg)
    elif a.kwonlyargs:
        parts.append("*")
    for arg, d in zip(a.kwonlyargs, a.kw_defaults):
        parts.append(arg.arg + (f"={ast.unparse(d)}" if d is not None else ""))
    if a.kwarg:
        parts.append("**" + a.kwarg.arg)
    return f"({', '.join(parts)})"


def is_public_enough(name):
    """Everything is documented, private helpers included — contributors need them
    too. Only dunder methods other than __init__ are skipped."""
    return not (name.startswith("__") and name.endswith("__") and name != "__init__")


def walk(path):
    """Yield (kind, qualified name, node, depth) for a module's documentable items."""
    tree = ast.parse(open(path, encoding="utf-8").read(), filename=path)
    yield "module", os.path.basename(path), tree, 0
    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            yield "class", node.name, node, 1
            for sub in node.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)) and is_public_enough(sub.name):
                    if any(ast.unparse(d).endswith(".setter") for d in sub.decorator_list):
                        continue  # documented on the property getter
                    yield "method", f"{node.name}.{sub.name}", sub, 2
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            yield "function", node.name, node, 1


def missing():
    """[(file, line, qualified name)] of items without a docstring."""
    out = []
    for fname, _title in MODULES:
        path = os.path.join(ROOT, fname)
        for kind, name, node, _d in walk(path):
            if kind == "method" and name.endswith(".__init__"):
                continue  # documented on the class
            if not ast.get_docstring(node):
                out.append((fname, getattr(node, "lineno", 1), name))
    return out


def render():
    """Build the Markdown text of docs/API.md."""
    lines = ["# API reference", "",
             "_Generated by `tools/gen_api_docs.py` from the docstrings — edit the code, "
             "not this file._", "",
             "For the big picture read [ARCHITECTURE.md](ARCHITECTURE.md) first.", "",
             "## Modules", ""]
    for fname, title in MODULES:
        anchor = fname.replace(".", "").replace("/", "").lower()
        lines.append(f"- [`{fname}`](#{anchor}) — {title}")
    lines.append("")

    for fname, title in MODULES:
        path = os.path.join(ROOT, fname)
        for kind, name, node, _depth in walk(path):
            doc = ast.get_docstring(node) or "_(undocumented)_"
            if kind == "module":
                lines += ["---", "", f"## {fname}", "", f"*{title}* · [source](../{fname})", "", doc, ""]
            elif kind == "class":
                bases = ", ".join(ast.unparse(b) for b in node.bases)
                init = next((s for s in node.body if isinstance(s, ast.FunctionDef) and s.name == "__init__"), None)
                sig = signature(init).replace("(self, ", "(").replace("(self)", "()") if init else ""
                lines += [f"### class `{name}{sig}`" + (f" ({bases})" if bases else ""), "",
                          f"<sub>{fname}:{node.lineno}</sub>", "", doc, ""]
                fields = [s for s in node.body if isinstance(s, ast.AnnAssign)]
                if fields:
                    lines.append("| Field | Type | Default |")
                    lines.append("|---|---|---|")
                    for f in fields:
                        default = ast.unparse(f.value) if f.value is not None else ""
                        lines.append(f"| `{ast.unparse(f.target)}` | `{ast.unparse(f.annotation)}` | `{default}` |")
                    lines.append("")
            elif kind == "method":
                if name.endswith(".__init__"):
                    continue
                cls, meth = name.split(".", 1)
                deco = [ast.unparse(d) for d in node.decorator_list]
                prefix = "property " if "property" in deco else ("static " if "staticmethod" in deco else
                                                                  "classmethod " if "classmethod" in deco else "")
                sig = signature(node).replace("(self, ", "(").replace("(self)", "()") \
                    .replace("(cls, ", "(").replace("(cls)", "()")
                if "property" in deco:
                    sig = ""
                lines += [f"#### {prefix}`{cls}.{meth}{sig}`", "", doc, ""]
            else:
                lines += [f"### `{name}{signature(node)}`", "", f"<sub>{fname}:{node.lineno}</sub>", "", doc, ""]
    return "\n".join(lines).rstrip() + "\n"


def main():
    """CLI entry: write docs/API.md, or with --check report undocumented items."""
    if "--check" in sys.argv:
        gaps = missing()
        for f, line, name in gaps:
            print(f"{f}:{line}: {name}")
        print(f"{len(gaps)} undocumented item(s)")
        return 1 if gaps else 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(render())
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
